name: e_commerce_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # تم التحديث لدعم Flutter 3.x و Null Safety

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Dependency Injection
  get_it: ^7.7.0 # تحديث من 3.0.3 (قديمة جداً)
  injectable: ^2.5.0

  # Networking & Data
  http: ^1.6.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5

  # UI & UX
  flutter_svg: ^2.0.10
  skeletonizer: ^2.1.3
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  animate_do: ^3.3.4
  toastification: ^2.0.0
  responsive_builder: ^0.7.1

  # State Management (يفضل استخدام Provider الحديث أو Bloc)
  provider: ^6.1.2 # تحديث من 3.2.0

  # Utils
  logger: ^2.4.0
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  marquee: ^2.3.0
  dots_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # تحديث ليتوافق مع المعايير الحالية
  build_runner: ^2.13.1
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  # أضف مسارات الصور هنا لو محتاجها
  assets:
    - assets/icons/
    - assets/image/
