// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:e_commerce_app/feature/cart/data/models/product_cart_model.dart';
import 'package:e_commerce_app/feature/favorite/data/models/product_favorite_model.dart';
import 'package:e_commerce_app/feature/home/data/models/products_response_dto.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ProductCartModelAdapter());
    registerAdapter(ProductFavoriteModelAdapter());
    registerAdapter(ProductsResponseDtoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ProductCartModelAdapter());
    registerAdapter(ProductFavoriteModelAdapter());
    registerAdapter(ProductsResponseDtoAdapter());
  }
}
